project:
  type: website

website:
  title: "Kowen Jeong"
  navbar:
    left:
      - href: about.qmd
        text: Content


format:
  html:
    theme:
      - lux
    css: styles.css
    toc: true

editor: visual

